### ISSUE TITLE
Use LRU cache in rudimentary ways

### ISSUE THREAD

**Issue by Moelf** [tamasgal/UnROOT.jl#12]
Probably for 2.0 release or something but I ran into some very light / nice implementation for example https://github.com/marius311/Memoization.jl .

I realized `uproot4` has dropped the way-too-many kinds of cache so we probably should learn from Jim in making one here. I think a good start would be to at leach cache whole `branch` / `tree` if they fit, in case users are doing some small exploration work.

For the larger-than-RAM TChain like event loop, cache is less useful:
1. user probably is running a script (so a one-off thing)
2. LRU cache is useless since accessed elements are >> RAM size.

**Comment by tamasgal** [comment]
Thanks Jerry, LRU is definitely on the feature-list and `Memoization.jl` looks definitely nice!

Yes, indeed, `uproot4` massively simplified the caching, we should definitely go that path ;)

**Comment by tamasgal** [comment]
Let's put it in v1 (hopefully in 2020)

**Comment by Moelf** [comment]
closed by #24, now we cache decompressed basketbytes basked on `(ROOTFile, branch, ith_basket)`
