### ISSUE TITLE
Better/safer printout

### ISSUE THREAD

**Issue by aminnj** [tamasgal/UnROOT.jl#120]
Sometimes I accidentally type `print(t)` in a script and then have to kill my terminal tab as millions of rows flood into stdout. 

We get a nice compact representation with the "default repr" in the REPL
```julia
julia> p
 Row │ nMuon   Muon_pt
     │ UInt32  SubArray{Float3
─────┼─────────────────────────
 1   │ 0       []
 2   │ 2       [19.9, 15.3]
 3   │ 0       []
 4   │ 0       []
 5   │ 0       []
 6   │ 0       []
 7   │ 2       [22.2, 4.43]
 8   │ 0       []
 9   │ 0       []
 10  │ 0       []
  ⋮  │   ⋮            ⋮
                90 rows omitted
```
which you can reproduce with `display(p)` or `println(repr(p, context=:limit=>true))`, the former of which is unintuitive for a newcomer and the latter unintuitive unless you spend 10 mins tracing through `show/display/repr` in Base.

I think pandas has a sane approach here:
```python
>>> import pandas as pd
>>> df = pd.DataFrame(range(1000))
>>> df
       0
0      0
1      1
2      2
3      3
4      4
..   ...
995  995
996  996
997  997
998  998
999  999

[1000 rows x 1 columns]
>>> print(df)
       0
0      0
1      1
2      2
3      3
4      4
..   ...
995  995
996  996
997  997
998  998
999  999

[1000 rows x 1 columns]
```
so, I propose that we match this behavior (always give compact output).

**Comment by tamasgal** [comment]
OK, I have mixed feelings about it 😅 I was always a bit annoyed that pandas skips rows when I do `print` because I usually would assume that `print` prints everything (in the old-sense of printing something on a physical printer, where you expect the whole thing and not skipping the middle part).

On the other hand, `numpy` does the same, so I understand the consistency issue. Maybe they started it and other devs just adopted it? Also, we don't have much fine-graded options for the "printer" like "from page 4-10", so my argument above is lacking a good foundation 😆

**Comment by Moelf** [comment]
>assume that print prints everything

I agree.

>for the "printer" like "from page 4-10"

I say we add this and other issues and one more for https://github.com/ronisbr/TerminalPager.jl as hacktoberfest 2021 ;)

**Comment by aminnj** [comment]
@tamasgal at the least we should always have some way of printing the full table. As a lifelong Python fan 😉, I'm a bit biased since `numpy`/`pandas` elide with all the main print methods (in a script and on the REPL) and then make it (only slightly harder) to show the full representation, since it's more common to summarize a table's structure than inspect all its values. Maybe this is even more so the case for julia because of its superior abilities for laziness :).

**numpy**
`a = np.arange(10000)`.
`a`/`print(a)` -- short output
`print(a.tolist())` -- full output

**pandas**
`df = pd.DataFrame(np.arange(1000))`
`df`/`print(df)` -- short output
`print(df.to_string())`, `df.style` (notebook) -- full output

**julia**
`t`/`display(t)`/`println(repr(p, context=:limit=>true))` -- short output
`show(t)`, `println(t)`, `repr(t)` -- full output

So I think it would be nice to swap the behavior of the two rows in julia so that we retain an easy way of fully dumping a table. But then that feels like a literal anti-pattern.

**Comment by aminnj** [comment]
@Moelf yeah, a `scan(t)` (or better word that doesn't give ROOT trauma) that shows a pager like `less`, and then making print elided by default, would solve this (for me at least)!

**Comment by Moelf** [comment]
We still need to think of a way to print a full table, `print(string(tree))` feels not Julia.

**Comment by aminnj** [comment]
Oh, I would've thought `print(string(tree))` makes sense (since there a step (`string()`) that explicitly materializes the full tree).

I can't say I like the `DataFrame` printout behavior either :(.

**Comment by aminnj** [comment]
so if we were like `DataFrames.jl` we should use show() and have a compact printout in the REPL and a script alike.

| `LazyTree` | REPL  | script |
| ---------- | ----- | ------ |
| `t`        | short | N/A    |
| `show`     | full  | full   |
| `println`  | full  | full   |
| `display`  | short | full   |

| `DataFrame` | REPL  | script |
| ----------- | ----- | ------ |
| `df`        | short | N/A    |
| `show`      | short | short  |
| `println`   | full  | full   |
| `display`   | short | full   |

**Comment by aminnj** [comment]
To summarize, the PR made our printing behavior consistent with DataFrames, so we now can and should be using `show`/`@show` in scripts to get compact printouts and `println` for the full printout.

**Comment by tamasgal** [comment]
Thanks! 🙃
