### ISSUE TITLE
`partitions` with `Arrow.write`

### ISSUE THREAD

**Issue by aminnj** [tamasgal/UnROOT.jl#123]
In the [past](https://gist.github.com/aminnj/79ceeb7ab9026f80e3cc1978124f8370), we used to be able to do

```julia
function Tables.partitions(t::LazyTree)
    # ...
    return (t[r] for r in ranges)
end
Arrow.write("out.arrow", t)
```

but now we need to use `innertable` to avoid a crash:
```diff
-Tables.partitions(t::LazyTree) = (t[r] for r in _clusterranges(t))
+Tables.partitions(t::LazyTree) = (innertable(t[r]) for r in _clusterranges(t))
```

which modifies the API if users want to have a `LazyTree` chunk from `partitions()` (Maybe it's OK?). I wonder if this is related to the DataFrames decoupling.

**Comment by Moelf** [comment]
I think there's merit in not mutating types during slicing and partition, i.e. return `LazyTree` wrapper and make it compatible with the table interface consistently.

I wonder why it breaks now

**Comment by aminnj** [comment]
Ah apparently we needed 
```julia
julia> Tables.columns(t::LazyTree) = NamedTuple((p,getproperty(t,p)) for p in propertynames(t))
```

**Comment by Moelf** [comment]
https://tables.juliadata.org/stable/#Implementing-the-Interface-(i.e.-becoming-a-Tables.jl-source)

ah yeah, we need to return a indexable, barebone column representation, this looks fine!
