### ISSUE TITLE
TLorentzVector branch support

### ISSUE THREAD

**Issue by Moelf** [tamasgal/UnROOT.jl#33]
@8me since you're looking at relevant code maybe I can borrow your wisdom! I'm trying to figure out the padding for TLorentz vector: https://github.com/scikit-hep/uproot3-methods/blob/ba9a97b3dc71c7030a9ec15a9d97397b5ff8aa0d/uproot3_methods/classes/TLorentzVector.py
```
import ROOT as r
from array import array

f = r.TFile("LorentzVector.root", "recreate")
t = r.TTree("t1","t1")

#x y z e
p4 = r.TLorentzVector(1,1,0,5)
t.Branch("LV.","TLorentzVector",p4)

for i in range(10):
     p4.SetPxPyPzE(1,1,0,i)
     t.Fill()
t.Write()
f.Close()
```

**Comment by 8me** [comment]
How do you get the 55 Bytes? When I do a:
```
julia> fobj = UnROOT.ROOTFile("test/samples/lorentzvector.root")
ROOTFile with 1 entry and 19 streamers.
test/samples/lorentzvector.root
└─ t1
   ├─ "LV."
   └─ ""

julia> data, offsets = UnROOT.array(fobj,"t1/LV."; raw=true)
(UInt8[0x40, 0x00, 0x00, 0x3c, 0x00, 0x04, 0x00, 0x01, 0x00, 0x00  …  0x00, 0x00, 0x40, 0xaf, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00], Int32[0, 64, 128, 192])

julia> reinterpret(Float64, data[offsets[2]:-1:offsets[1]+1])[end:-1:1]
8-element Vector{Float64}:
  2.0001144410343845
  2.4867138e-316
  2.000068664638093
  2.4867138e-316
 10.0
 20.0
 30.0
 40.0
```
So the fields of the `TLorentzVector` we should have with that, isn't it?

**Comment by tamasgal** [comment]
Just for reference, this is the first entry (should be `[1, 2, 3, 4]`):

```python
In [6]: import uproot3

In [7]: f = uproot3.open("lorentzvector.root")

In [8]: f["t1/LV"].array(uproot3.asdebug)[0]
Out[8]:
array([ 64,   0,   0,  60,   0,   4,   0,   1,   0,   0,   0,   0,   3,
         0,   0,   0,  64,   0,   0,  36,   0,   3,   0,   1,   0,   0,
         0,   0,   3,   0,   0,   0,  63, 240,   0,   0,   0,   0,   0,
         0,  64,   0,   0,   0,   0,   0,   0,   0,  64,   8,   0,   0,
         0,   0,   0,   0,  64,  16,   0,   0,   0,   0,   0,   0],
      dtype=uint8)
```

**Comment by 8me** [comment]
Please note, that I used the example by @tamasgal without the `Fill` after the first entry, so in my reference file the first entry should be `[10,20,30,40]`

**Comment by tamasgal** [comment]
Just take the file from the `lorentzvector` branch (there is also the exact script) ;)

**Comment by Moelf** [comment]
![image](https://user-images.githubusercontent.com/5306213/125369072-d0e3ba80-e37b-11eb-99c5-4b6a84d87189.png)

I don't like how I got there though....I think we should re structure our code such that user only needs to specialize on:
https://github.com/tamasgal/UnROOT.jl/blob/74735c939e4127ee527270b21be9cd19626566f9/src/root.jl#L150
and
https://github.com/tamasgal/UnROOT.jl/blob/74735c939e4127ee527270b21be9cd19626566f9/src/root.jl#L185

to fully teaches us how to reinterpret the bytes. (`JaggType` can be easily merged into the latter and just return `(type, jaggtype)` instead and don't call `JaggType` individually

**Comment by aminnj** [comment]
Hi,

There's another kind of LorentzVector that people use (~rare use case):
```cpp
  fClassName: String "ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<float> >"
```

(which uses float instead of double to save on space, and is more easily compressible in (pt,eta,phi,m) vs (px,py,pz,e) format)

I doubt it's going to be as easy to parse as `TLorentzVector`, but for future reference, a file can be made with
```python
#!/usr/bin/env python
import ROOT as r
f = r.TFile("lorentzvector.root", "recreate")
t = r.TTree("t1","t1")
p4 = r.Math.LorentzVector(r.Math.PtEtaPhiM4D(float))()
t.Branch("LV", p4.__cppname__, p4)
for i in range(1, 4):
    p4.SetPt(25+i*5,)
    p4.SetEta(1.1+i*0.1)
    p4.SetPhi(-1.1-i*0.1)
    p4.SetM(91)
    t.Fill()
t.Write()
f.Close()
```
```C++
root [3] t1->Scan("LV.Pt()")
************************
*    Row   *   LV.Pt() *
************************
*        0 *        30 *
*        1 *        35 *
*        2 *        40 *
************************
```
