### ISSUE TITLE
[Discussion] Potential existing wheel for jagged array

### ISSUE THREAD

**Issue by Moelf** [tamasgal/UnROOT.jl#5]
I stumped upon https://github.com/andyferris/Dictionaries.jl and saw this:
```
julia> dict = Dictionary(["a", "b", "c"], [1, 2, 3])
3-element Dictionary{String,Int64}
 "a" │ 1
 "b" │ 2
 "c" │ 3

julia> dict .+ 1
3-element Dictionary{String,Int64}
 "a" │ 2
 "b" │ 3
 "c" │ 4
```

and performance is an aim for the package so I thought this can be a solid base for jagged array.

**Comment by tamasgal** [comment]
Yes thanks, that looks interesting! I am however still wondering if jaggedness is really an issue in Julia 🤔 So far I am working with `UnROOT` using arrays of arrays (coming from the yet undocumented `splitup()` method) for my own analysis and readout is around 2x faster compared to `uproot`.

I think the only benefits of using something more fancy than bare arrays is the fancy indexing, to access a sparse set of deeply nested structures very efficiently, just like in a multi dimensional matrix; and the laziness which we definitely need when working with large and/or unsplit branches which do not fit into memory.

**Comment by Moelf** [comment]
I think a good benchmark would be say, you have a tree that contains vector of lepton `p4`s (so you can have 0 leptons, `[]`, or like 10 of them), then you try to loop through, find the two 4 vectors that sums whose invariant mass is closest to a `Z` mass, the make the histogram.

I think `uproot` you can probably do this in 1-2 lines and be pretty fast.

**Comment by tamasgal** [comment]
In `uproot` you are basically totally tied to high level functions which need to call some kind of vectorised or at least precompiled and optimised routines. Jim showed a few examples how to use `awkward1` to do such search in one of his presentations. I am quite confident that in Julia you can just write a simple for-loop and have comparable or even better performance.
Of course, high-level functions make look these things much nicers 😉 

That would indeed be a nice test. Do you happen to have such a file around? I can of course also look into some `uproot` demo notebooks...
