### ISSUE TITLE
`leaf.fLenType==0` falsely classifying jagged branch as non-jagged

### ISSUE THREAD

**Issue by aminnj** [tamasgal/UnROOT.jl#61]
So I came across a super weird issue. I couldn't open up an analysis ntuple with a pretty basic type (`vector<float>`). Apparently this depends on the environment 😕. Test file:
```python
import ROOT as r

f = r.TFile("output_good.root", "recreate")
t = r.TTree("Events", "")

obj = r.vector("float")()
t.Branch("Jet_pt", obj)

rows = [[], [27.324586868286133, 24.88954734802246, 20.853023529052734], [], [20.330659866333008], [], []]
for row in rows:
    obj.clear()
    for x in row:
        obj.push_back(x)
    t.Fill()
t.Write()
f.Close()
```
gives me
```julia
julia> ROOTFile("output_good.root")["Events/Jet_pt"]
6-element LazyBranch{Vector{Float32}, UnROOT.Offsetjagg}:
 []
 [27.324587, 24.889547, 20.853024]
 []
 [20.33066]
 []
 []
```
if I make the ntuple on my laptop (MacOS, Python3, ROOT 6.16/00). But it fails with
```julia
julia> ROOTFile("output_bad.root")["Events/Jet_pt"]
6-element LazyBranch{Vector{Float32}, UnROOT.Nojagg}:
Error showing value of type LazyBranch{Vector{Float32}, UnROOT.Nojagg}:
ERROR: MethodError: Cannot `convert` an object of type Float32 to an object of type Vector{Float32}
```
if I make the ntuple on a remote machine in a CMS environment (SLC7/`CMSSW_10_2_5`, Python2.7 😬, ROOT 6.12/07).

Raw bytes are the same according to `array(...; raw=true)`. The only difference I found was that `fLeaves` on that branch has
```julia
  fLenType: Int32 4 # "bad"/remote ntuple
  fLenType: Int32 0 # "good"/local ntuple
```
which means that 
```julia
function JaggType(leaf)
    # https://github.com/scikit-hep/uproot3/blob/54f5151fb7c686c3a161fbe44b9f299e482f346b/uproot3/interp/auto.py#L144
    (match(r"\[.*\]", leaf.fTitle) !== nothing) && return Nooffsetjagg
    leaf isa TLeafElement && leaf.fLenType==0 && return Offsetjagg
    return Nojagg
end
```
mis-classifies it as a `Nojagg` branch because of the `leaf.fLenType==0`. Given that uproot4 can read both ntuples just fine, is there a way around the `fLenType` check, or an alternative? Note that the `fLenType` was introduced to deal with this case: https://github.com/tamasgal/UnROOT.jl/issues/55 . So we'll have to revisit that...

**Comment by aminnj** [comment]
I'm guessing `leaf.fLenType==0` will have to be replaced with an `OR` of 
https://github.com/scikit-hep/uproot3/blob/54f5151fb7c686c3a161fbe44b9f299e482f346b/uproot3/interp/auto.py#L144
and the long if-else here
https://github.com/scikit-hep/uproot3/blob/54f5151fb7c686c3a161fbe44b9f299e482f346b/uproot3/interp/auto.py#L360-L369

**Comment by 8me** [comment]
@aminnj can you add the "bad" file to the test samples or at least make it somehow available?

**Comment by aminnj** [comment]
Sorry, I uploaded them here:
http://uaf-7.t2.ucsd.edu/~namin/dump/output_good.root
http://uaf-7.t2.ucsd.edu/~namin/dump/output_bad.root

**Comment by tamasgal** [comment]
Ouhm... that's very funny indeed. I guess stepping through https://github.com/tamasgal/UnROOT.jl/issues/61#issuecomment-885470955 with the debugger would reveal things. I assume this is coming from some backward-compatibility implementations, probably related to the PyROOT version for Python 2.7, but I am just guessing. At least, many of the weird "multiple ways to do the same thing" in ROOT are coming from backward compatibility efforts...

**Comment by aminnj** [comment]
Uproot figures out the jaggedness through this path...
```python
if getattr(branch._streamer, "_fSTLtype", None) == uproot3.const.kSTLvector:
    try:
        fromdtype = _ftype2dtype(branch._streamer._fCtype, awkward0)
        if swapbytes:
            ascontent = asdtype(fromdtype, fromdtype.newbyteorder("="))
        else:
            ascontent = asdtype(fromdtype, fromdtype)
        if branch._isTClonesArray:
            return asgenobj(SimpleArray(STLVector(asdtype(fromdtype, fromdtype))), branch._context, 6)
        else:
            return asjagged(ascontent, skipbytes=10) # <------ HERE
```
which I'm not sure how to replicate in `UnROOT`. Though I have to say, excepting these edge cases, the current 3 line `JaggType` seems comparable to a few hundred lines in `uproot3/auto.py` :)

**Comment by tamasgal** [comment]
Sorry that I cannot look myself now, but have you had a look at the streamers for both files? There has to be some differences... 🤔

**Comment by aminnj** [comment]
No problem. I'll take a look in the morning and hopefully it's not a huge rabbit hole 🤞

**Comment by tamasgal** [comment]
😆 what is not a rabbit hole in ROOT 😉 

The streamer information is stored in a simple struct, so that should be easy to compare. I'll also try to find a bit of time to investigate

**Comment by tamasgal** [comment]
The streamer info for `vector<float>` are identical...

```julia
julia> UnROOT.streamerfor(fgood, "vector<float>")
UnROOT.StreamerInfo(UnROOT.TStreamerInfo{UnROOT.TObjArray}("vector<float>", "", 0x055a169b, 6, UnROOT.TObjArray("", 0, Any[UnROOT.TStreamerSTL
  version: UInt16 0x0004
  fOffset: Int64 0
  fName: String "This"
  fTitle: String "<Float_t> Used to call the proper TStreamerInfo case"
  fType: Int32 500
  fSize: Int32 0
  fArrayLength: Int32 0
  fArrayDim: Int32 0
  fMaxIndex: Array{Int32}((5,)) Int32[0, 0, 0, 0, 0]
  fTypeName: String "vector<float>"
  fXmin: Float64 0.0
  fXmax: Float64 0.0
  fFactor: Float64 0.0
  fSTLtype: Int32 1
  fCtype: Int32 5
])), Set{Any}())

julia> UnROOT.streamerfor(fbad, "vector<float>")
UnROOT.StreamerInfo(UnROOT.TStreamerInfo{UnROOT.TObjArray}("vector<float>", "", 0x055a169b, 6, UnROOT.TObjArray("", 0, Any[UnROOT.TStreamerSTL
  version: UInt16 0x0004
  fOffset: Int64 0
  fName: String "This"
  fTitle: String "<Float_t> Used to call the proper TStreamerInfo case"
  fType: Int32 500
  fSize: Int32 0
  fArrayLength: Int32 0
  fArrayDim: Int32 0
  fMaxIndex: Array{Int32}((5,)) Int32[0, 0, 0, 0, 0]
  fTypeName: String "vector<float>"
  fXmin: Float64 0.0
  fXmax: Float64 0.0
  fFactor: Float64 0.0
  fSTLtype: Int32 1
  fCtype: Int32 5
])), Set{Any}())
```

**Comment by Moelf** [comment]
>mis-classifies it as a Nojagg branch because of the leaf.fLenType==0

do you mean mis-classfied as Nojagg because `fLenType != 0`?

If `leaf isa TLeafElement` still holds true, we can simply change `&&` to `||` in that line?

**Comment by aminnj** [comment]
Yep, I was referring to the if statement condition `leaf.fLenType==0` which fails because for the "bad" file, it's 4.


Unfortunately, we used `&& leaf.fLenType==0` to prevent the `Nojagg` branch in https://github.com/tamasgal/UnROOT.jl/issues/55 from being classified as `Offsetjagg` because:
```julia
julia> f = ROOTFile("/Users/namin/.julia/dev/UnROOT/test/samples/cms_ntuple_wjet.root")
julia> UnROOT.array(rootfile, "variable/met_p4/fCoordinates/fCoordinates.fPt"; raw=false)
leaf isa TLeafElement = true
leaf.fLenType = 4
```

We could add a line like (with a try-except for base types)
```julia
(streamerfor(f, branch.fClassName).fSTLtype == Const.kSTLvector) && return Offsetjagg
```
but since the streamer isn't "attached" to the branch itself, that would require passing through the file object through `JaggType` and all the `auto_T_JaggT`s.

**Comment by Moelf** [comment]
>that would require passing through the file object through JaggType and all the auto_T_JaggTs.

not necessarily a bad idea if it is what has to be done.
