### ISSUE TITLE
Missing struct TLeafD

### ISSUE THREAD

**Issue by bernd1995** [tamasgal/UnROOT.jl#7]
I was trying to do some basic IO to Julia of my ROOT-Files, however my Branches could not be read.
It turned out that the basic problem is that I am storing my variables in the Root-Branches as 64-bit floats (doubles)  which is not supported by UnROOT yet.

Therefore I get the following Error-Message:
`ERROR: UndefVarError: TLeafD not defined`

I added a small ROOT-File ([test.root.zip](https://github.com/tamasgal/UnROOT.jl/files/5103539/test.root.zip))
 with 2 TTrees (TreeF and TreeD) with 32-bit floats and 64-bit floats. TreeF can be read into Julia without a problem but TreeD throws the above mentioned error.

If I got this correctly, a simple fix would be just adding the struct in `TLeafD` in bootstrap.jl but I haven't looked thoroughly through the entire Source-Code to verify this.

I would be really grateful if this could be fixed, so I can use Julia for processing my ROOT-Files. Thanks in advance.

**Comment by tamasgal** [comment]
Thanks Bernd for reporting the issue and providing the sample file. Indeed `TLeafD` was not defined yet and the right place is `bootstrap.jl`. I just added the definition in https://github.com/tamasgal/UnROOT.jl/commit/cbb55a24bc5ad33c2a5633d6d28d6193caf8e8a6 and was able to read your branch:

```julia
julia> using UnROOT

julia> f = ROOTFile("test/samples/issue7.root")
ROOTFile("test/samples/issue7.root") with 2 entries and 17 streamers.

julia> keys(f)
2-element Array{String,1}:
 "TreeD"
 "TreeF"

julia> keys(f["TreeD"])
1-element Array{String,1}:
 "nums"

julia> array(f, "TreeD/nums")
3-element Array{Float64,1}:
 1.0
 2.0
 3.0
```

Let me know if you encounter further problems!

**Comment by tamasgal** [comment]
I also created a new tag (v0.1.5) which will be released within the next hour automatically, so you can `Pkg.update("UnROOT")`.

**Comment by bernd1995** [comment]
Thanks for the really fast reply and fix.
Tested it with my files and it works as expected.
