### ISSUE TITLE
Reading Branches from TNtuples

### ISSUE THREAD

**Issue by bernd1995** [tamasgal/UnROOT.jl#8]
I ran across another (small) issue.

Most of the times my data in root-files is stored in `TTrees` since these permit to store different datatypes into one collection. However for storing some settings (like Random-Number-Generator Seeds) I prefer to store the values in `TNtuples` which is similar to `TTrees` but only allows to store 32-bit floats. 

Since the `TKey` of a `TNtuple` differs from a `TTree` the `array()` is not able to process the entries. 

I added again a small file ([test.root.zip](https://github.com/tamasgal/UnROOT.jl/files/5108296/test.root.zip)) with the same data stored once in a `TTree` and once in a `TNtuple`.

It would be helpful to add support for TNtuples. In principle this should not differ much from a `TTree` with a `TBranch` containing `TLeafF` objects.

**Comment by tamasgal** [comment]
I have to increase the priority for this... I got already multiple requests to add this feature
